In [63]:
import numpy as np
from math import cos, sin

In [64]:
def det(M):
    return M[0,0]*M[1,1]*M[2,2]+M[1,0]*M[2,1]*M[0,2]+M[2,0]*M[0,1]*M[1,2] - M[0,2]*M[1,1]*M[2,0]-M[0,0]*M[1,2]*M[2,1]-M[0,1]*M[1,0]*M[2,2]

# Test of directional unit vector approach instead of vector theta.

In [65]:
omega = np.array([0.2, 0.4, 0.16])
theta = [0.5, 1.0, 1.5]
dt = 0.1

In [66]:
Sigma = np.asmatrix([[0, -omega[2], omega[1]],
            [omega[2], 0, -omega[0]],
            [-omega[1], omega[0], 0]])

In [67]:
R = np.identity(3) + Sigma * dt
R

matrix([[ 1.   , -0.016,  0.04 ],
        [ 0.016,  1.   , -0.02 ],
        [-0.04 ,  0.02 ,  1.   ]])

In [68]:
det(R)

np.float64(1.0022559999999998)

In [69]:
v1 = np.array([1,0,0]).reshape(-1, 1)
v1

array([[1],
       [0],
       [0]])

In [70]:
v2 = R * v1
v2

matrix([[ 1.   ],
        [ 0.016],
        [-0.04 ]])

In [71]:
R*v2

matrix([[ 0.998144],
        [ 0.0328  ],
        [-0.07968 ]])

# Original approach - failed

In [72]:
Mx = np.asmatrix([[1, 0, 0],
              [0, cos(theta[0]), -1*sin(theta[0])],
              [0, sin(theta[0]), cos(theta[0])]
              ])

In [73]:
Mx

matrix([[ 1.        ,  0.        ,  0.        ],
        [ 0.        ,  0.87758256, -0.47942554],
        [ 0.        ,  0.47942554,  0.87758256]])

In [74]:
My = np.asmatrix([[cos(theta[1]), 0, sin(theta[1])],
              [0, 1, 0],
              [-1*sin(theta[1]), 0, cos(theta[1])]
              ])

In [75]:
My

matrix([[ 0.54030231,  0.        ,  0.84147098],
        [ 0.        ,  1.        ,  0.        ],
        [-0.84147098,  0.        ,  0.54030231]])

In [76]:
Mz = np.asmatrix([[cos(theta[2]), -1*sin(theta[2]), 0],
              [sin(theta[2]), cos(theta[2]), 0],
              [0, 0, 1]
              ])

In [77]:
Mz

matrix([[ 0.0707372 , -0.99749499,  0.        ],
        [ 0.99749499,  0.0707372 ,  0.        ],
        [ 0.        ,  0.        ,  1.        ]])

In [78]:
Mx * My * Mz

matrix([[ 0.03821947, -0.53894884,  0.84147098],
        [ 0.9039212 , -0.34033437, -0.25903472],
        [ 0.42598796,  0.77052363,  0.47415988]])

In [79]:
Mx * Mz * My

matrix([[ 0.03821947, -0.99749499,  0.0595233 ],
        [ 0.87639479,  0.06207773,  0.47757569],
        [-0.48007442,  0.03391322,  0.87657198]])

In [80]:
M = Mx * My * Mz

In [81]:
# M = np.mat([[1 + cos(theta[1]) + cos(theta[2]), -1*sin(theta[2]), sin(theta[1])],
            #   [sin(theta[2]), 1 + cos(theta[0]) + cos(theta[2]), -1*sin(theta[0])],
            #   [-1*sin(theta[1]), sin(theta[0]), 1 + cos(theta[0]) + cos(theta[1])]
            #   ])

In [82]:
M

matrix([[ 0.03821947, -0.53894884,  0.84147098],
        [ 0.9039212 , -0.34033437, -0.25903472],
        [ 0.42598796,  0.77052363,  0.47415988]])

In [83]:
M[0,0]*M[1,1]*M[2,2]+M[1,0]*M[2,1]*M[0,2]+M[2,0]*M[0,1]*M[1,2] - M[0,2]*M[1,1]*M[2,0]-M[0,0]*M[1,2]*M[2,1]-M[0,1]*M[1,0]*M[2,2]

np.float64(1.0000000000000002)

In [84]:
v1 = np.array([1,0,0])

In [85]:
v1.reshape(-1,1)

array([[1],
       [0],
       [0]])

In [86]:
v2 = M * v1.reshape(-1, 1)
v2

matrix([[0.03821947],
        [0.9039212 ],
        [0.42598796]])

In [87]:
Mz*My*Mx*v1.reshape(-1 , 1)

matrix([[ 0.03821947],
        [ 0.53894884],
        [-0.84147098]])

In [88]:
v2[0]**2 + v2[1]**2 + v2[2]**2

matrix([[1.]])