In [1]:
import numpy as np
from math import cos, sin

In [9]:
def det(M):
    return M[0,0]*M[1,1]*M[2,2]+M[1,0]*M[2,1]*M[0,2]+M[2,0]*M[0,1]*M[1,2] - M[0,2]*M[1,1]*M[2,0]-M[0,0]*M[1,2]*M[2,1]-M[0,1]*M[1,0]*M[2,2]

# Test of directional unit vector approach instead of vector theta.

In [15]:
omega = np.array([0.2, 0.4, 0.16])
dt = 0.1

In [16]:
Sigma = np.mat([[0, -omega[2], omega[1]],
            [omega[2], 0, -omega[0]],
            [-omega[1], omega[0], 0]])

In [17]:
R = np.identity(3) + Sigma * dt
R

matrix([[ 1.   , -0.016,  0.04 ],
        [ 0.016,  1.   , -0.02 ],
        [-0.04 ,  0.02 ,  1.   ]])

In [18]:
det(R)

1.0022559999999998

In [7]:
v1 = np.array([1,0,0]).reshape(-1, 1)
v1

array([[1],
       [0],
       [0]])

In [8]:
v2 = R * v1
v2

matrix([[ 1.0e+00],
        [ 1.6e-05],
        [-4.0e-05]])

In [19]:
R*v2

matrix([[ 0.99999814],
        [ 0.0160168 ],
        [-0.04003968]])

# Original approach - failed

In [83]:
Mx = np.mat([[1, 0, 0],
              [0, cos(theta[0]), -1*sin(theta[0])],
              [0, sin(theta[0]), cos(theta[0])]
              ])

In [84]:
Mx

matrix([[ 1.        ,  0.        ,  0.        ],
        [ 0.        ,  0.98006658, -0.19866933],
        [ 0.        ,  0.19866933,  0.98006658]])

In [85]:
My = np.mat([[cos(theta[1]), 0, sin(theta[1])],
              [0, 1, 0],
              [-1*sin(theta[1]), 0, cos(theta[1])]
              ])

In [86]:
My

matrix([[ 0.92106099,  0.        ,  0.38941834],
        [ 0.        ,  1.        ,  0.        ],
        [-0.38941834,  0.        ,  0.92106099]])

In [87]:
Mz = np.mat([[cos(theta[2]), -1*sin(theta[2]), 0],
              [sin(theta[2]), cos(theta[2]), 0],
              [0, 0, 1]
              ])

In [88]:
Mz

matrix([[ 0.98722728, -0.15931821,  0.        ],
        [ 0.15931821,  0.98722728,  0.        ],
        [ 0.        ,  0.        ,  1.        ]])

In [89]:
Mx * My * Mz

matrix([[ 0.90929654, -0.14674179,  0.38941834],
        [ 0.23251976,  0.95522274, -0.18298657],
        [-0.34512948,  0.25693652,  0.9027011 ]])

In [90]:
Mx * Mz * My

matrix([[ 0.90929654, -0.15931821,  0.38444441],
        [ 0.2211822 ,  0.96754847, -0.12218184],
        [-0.35250281,  0.19613178,  0.91502683]])

In [91]:
M = Mx * My * Mz

In [92]:
# M = np.mat([[1 + cos(theta[1]) + cos(theta[2]), -1*sin(theta[2]), sin(theta[1])],
            #   [sin(theta[2]), 1 + cos(theta[0]) + cos(theta[2]), -1*sin(theta[0])],
            #   [-1*sin(theta[1]), sin(theta[0]), 1 + cos(theta[0]) + cos(theta[1])]
            #   ])

In [93]:
M

matrix([[ 0.90929654, -0.14674179,  0.38941834],
        [ 0.23251976,  0.95522274, -0.18298657],
        [-0.34512948,  0.25693652,  0.9027011 ]])

In [94]:
M[0,0]*M[1,1]*M[2,2]+M[1,0]*M[2,1]*M[0,2]+M[2,0]*M[0,1]*M[1,2] - M[0,2]*M[1,1]*M[2,0]-M[0,0]*M[1,2]*M[2,1]-M[0,1]*M[1,0]*M[2,2]

1.0

In [95]:
v1 = np.array([1,0,0])

In [96]:
v1.reshape(-1,1)

array([[1],
       [0],
       [0]])

In [100]:
v2 = M * v1.reshape(-1, 1)
v2

matrix([[ 0.90929654],
        [ 0.23251976],
        [-0.34512948]])

In [ ]:
Mz*My*Mx*v1.reshape(-1 , 1)

matrix([[ 0.90929654],
        [ 0.14674179],
        [-0.38941834]])

In [101]:
v2[0]**2 + v2[1]**2 + v2[2]**2

matrix([[1.]])